sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/nim-ui-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-ui-base run "nimble install -y && nake --norun && nake js -d:release --norun" && ./deployGHPages.sh ./build/js
